spec: specs/tensor_spec.yaml
train:
  steps: 50
  batch: 32
  q: 4
  L: 2
  noise: false
  out: reports/reupload_params.json
  # data: data/train.csv
  # val_data: data/val.csv
predict:
  params: reports/reupload_params.json
  n: 5
  seed: 0
  export: reports/predict_example.json
eval:
  params: reports/reupload_params.json
  # data: data/dataset.csv  # optional; if omitted uses toy fallback
  seed: 0
  export: reports/eval_predictions.json
  # input: path/to/vectors.json
